### ISSUE TITLE
Compiling for RasPi

### ISSUE THREAD

**Issue by nanofortran** [sictransit/wefax#1]
I'd like to compile this for Raspberry Pi, but not sure how to navigate the C#. Any suggestions? Thanks!

**Comment by nanofortran** [comment]
Update: short answer is to install dotnet (v. 3.1): [one solution](https://medium.com/@alienratt/installing-net-core-sdk-3-1-on-the-raspberry-pi-4152ba5e6cfb) I tried the latest version 6.0 and got a warning to step back to 3.1. 

Also might need to pick up `libgdiplus` for the build. (It wasn't in Ubuntu 20.04 or latest PiOS)
`sudo apt-get install libgdiplus`.

Then extract the source and do a `dotnet build `folowed by a `dotnet run`. This works well, image is pretty stable, will see how it goes with VHF over the next few days.

Any additional command line `-commands` I should know about, or does it just `'do it'`?

**Comment by sictransit** [comment]
I'm glad you've found my little project. It was created as a "hack" for an amateur radio Geocaching project, nothing more than that. 

Today I've changed target to net6.0 and added basic command line arguments, e.g. a source image filename. I haven't tried to build or run it on an RPi and I suspect System.Drawing might be a bit troublesome. However, the audio library shouldn't have any dependencies to Windows.

Feel free to suggest improvements, fork or submit a pull request. I will not promise to spend a lot of time on this though.

73's de SM5SYO

**Comment by sictransit** [comment]
System.Drawing has now been replaced with ImageSharp.
