### ISSUE TITLE
120 LPM possible?

### ISSUE THREAD

**Issue by nanofortran** [sictransit/wefax#5]
Still playing around with this, all working well after the update. A few things, using fldigi's WeFax TX as reference, is it possible to adjust the Lines Per Minute LPM (currently it seems to be going a bit fast, maybe its set for 240 LPM? We can achieve clearer images with a slower LPM, so is it possible to adjust the LPM output?) and is this following the WEFAX-IOC576 protocol or IOC-288 (again, these are the choices with fldigi). For my project I am creating a remote automated camera/raspberry pi that is transmitting periodically on 70cm to a gallery and I am looking for an embedded replacement for fldigi (which is difficult to script with few CLI options, etc.)

Thanks again for this lovely work, it works quite well.

Jason

**Comment by nanofortran** [comment]
BTW, have tested with two Baofangs and a Raspi, the images come through the air to my phone app very well. For our gallery work, however, we are actually using a modern WeFax machine, which my collaborator has shown to work using .wav files generated by your software.

**Comment by nanofortran** [comment]
A final tidbit, 60LPM is even clearer/cleaner for our project purposes.

Thanks again,

Jason

**Comment by sictransit** [comment]
Thank you for your appreciation. I'm quite curious to what you are building. It seems like an interesting project. 

I've never had access to real WeFax hardware, so the only tests I've done is with various software receivers. 

Regarding your questions:

The implementation should be IOC576 at 120 lpm (giving a horisontal resolution of 576 x pi). That's what the input image will be scaled to (-5% for the white bar to the left).

I'm not sure how to go to 60? The documentation on this topis is quite sparse, so my implementation is basically pieces of info found here and there, patched with some guesswork and testing.

If you generate a wav file using the supplied test image, it will be 694 seconds long. That sums up well:

- 5 secs start
- 20 secs phasing
- 1328 lines at 120 lpm = 664 secs
- 5 secs stop

If you look at a spectrogram at the end of the transmission, it seems to line up well with one line at even 500 ms (even after 11 minutes):

![image](https://user-images.githubusercontent.com/4610247/175214826-49092974-5636-4a39-a89b-392b66f3e02f.png)

Keep me posted! I'll keep this issue open for now.

**Comment by sictransit** [comment]
@nanofortran Should I consider this issue as resolved with respect to my comment above?
